### ISSUE TITLE
Would be nice to be able to track packets from multiple interfaces simultaneously

### ISSUE THREAD

**Issue by jariarkko** [EricssonResearch/spindump#127]

**Comment by MaximProshin** [comment]
would it be enough to support "any" device (DLT_LINUX_SLL) option, i.e. capture from all interfaces, or do you want to specify particular interfaces after -i ?

**Comment by MaximProshin** [comment]
"any" device option has been added in #174.

**Comment by jariarkko** [comment]
Added in commit 6148c1e by @MaximProshin
