### ISSUE TITLE
reordering

### ISSUE THREAD

**Issue by sznadas** [EricssonResearch/spindump#129]
rtt measurement should work in case of moderate reordering
similarly, support for reordering shall be added for selected loss detection methods

**Comment by sznadas** [comment]
Done for spin trasitions.

Not yet done for qrloss. There is a methodf, but that needs to look into the history.

**Comment by ihlar** [comment]
I believe this issue is addressed in #44, for RTT. Suggest adding a new issue for reodering robustness for qr-loss.
