### ISSUE TITLE
Automatic tests fail on the currently checked in master version

### ISSUE THREAD

**Issue by jariarkko** [EricssonResearch/spindump#134]

**Comment by ihlar** [comment]
Does it only fail on OSX?
On Ubuntu 16.04 the tests pass.

**Comment by jariarkko** [comment]
Good question. I get an assertion failure when doing "make test", on one of the tests. Will solve in a bit.

**Comment by jariarkko** [comment]
(Could also be unrelated to rtloss. Will know in a bit)

**Comment by jariarkko** [comment]
Wasn't related to rtloss, maybe related to better assertions, not quite sure why this wasn't seen before. But in any case, now it is corrected.

**Comment by jariarkko** [comment]
Solved in commit 2a74540
