### ISSUE TITLE
Fix LGTM nits

### ISSUE THREAD

**Issue by larseggert** [EricssonResearch/spindump#162]
See https://lgtm.com/projects/g/EricssonResearch/spindump/

**Comment by jariarkko** [comment]
Tentatively resolved in commit ef85d47 but need to wait 24 hours to see if the LGTM refresh verifies all issues as corrected.

**Comment by jariarkko** [comment]
LGTM says: 

Excellent, there aren't any alerts for EricssonResearch/spindump right now!
