### ISSUE TITLE
Spindump crash upon terminal resizing

### ISSUE THREAD

**Issue by jariarkko** [EricssonResearch/spindump#188]
Szilvester Nadas reports: An interesting spindump bug:

1 connections 1 packets 72 bytes (showing latest RTTs, not showing UDP)

TYPE    ADDRESSES SESSION                        STATE   PAKS   LEFT RTT  RIGHT RTT  NOTE
spindump: fatal error: Assertion failed on /home/eszinda/quic_meas/spindump/src/spindump_connections_print.c line 499 -- exit
                        eszinda@vbsz1804:~$ 
 

The terminal also freezes pretty consistntly works on my vm: start spindump, start chrome, this happens
Newest repo, ubuntu 1804
was workng before though

**Comment by jariarkko** [comment]
Also if I just resize the window there is no issu, the issue only happens if I resize it using windows-"left arrow".

**Comment by sznadas** [comment]
Was an issue in an old version, works fine in the newest version.
