### ISSUE TITLE
Spindump does not always show port pairs for Google QUIC

### ISSUE THREAD

**Issue by jariarkko** [EricssonResearch/spindump#189]
But is the json dependent on screen size?
    { "Event": "new", "Type": "QUIC", "Addrs": ["10.0.2.15","216.58.214.238"], "Session": "null-null", "Ts": "1585750957531256" }
 
    Just wondering what the root cause is that there is no version, UDP port, or setup RTT here
    might be an unspported version
    I use the newest Chrome

**Comment by sznadas** [comment]
Was an issue in an old version, works fine in the newest version.
